{"name":"checkLimitOfReturnValues","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Фактическое значение отлично от ожидаемого expected [29] but found [10]","trace":"java.lang.AssertionError: Фактическое значение отлично от ожидаемого expected [29] but found [10]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:136)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:839)\r\n\tat apiTests.SectionNameApiTests.checkLimitOfReturnValues(SectionNameApiTests.java:40)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1507)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:770)\r\n\tat org.testng.TestRunner.run(TestRunner.java:591)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)\r\n"},"stage":"finished","description":"Проверка лимита вернувшихся значений","steps":[],"attachments":[],"parameters":[],"start":1594710234406,"stop":1594710236361,"uuid":"39ac998f-fdc9-4580-b961-04ec981aaa0f","historyId":"dbc4042235006d62a3029a7ad4d9e72d","fullName":"apiTests.SectionNameApiTests.checkLimitOfReturnValues","labels":[{"name":"package","value":"apiTests.SectionNameApiTests"},{"name":"testClass","value":"apiTests.SectionNameApiTests"},{"name":"testMethod","value":"checkLimitOfReturnValues"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"TestTaskOneTwoTrip"},{"name":"subSuite","value":"apiTests.SectionNameApiTests"},{"name":"host","value":"msk-2149"},{"name":"thread","value":"13428@msk-2149.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[]}